site:
  title: Implicated
  url: https://docs.implicated.com
  start_page: open-feign::index.adoc
content:
  sources:
    - url: ../feign-docs
      start_paths:
        - docs
      branches: HEAD
ui:
  bundle:
    url: https://raw.githubusercontent.com/implicated/asciidoc-publish-template/ui/ui-bundle.zip?raw=true
    snapshot: true
runtime:
  fetch: true
  cache_dir: ./.cache/antora
  log:
    failure_level: error
output:
  clean: true

antora:
  extensions:
    - require: '@antora/lunr-extension'
asciidoc:
  extensions:
    - asciidoctor-kroki
    - asciidoctor-highlight.js/
  attributes:
    experimental: ''
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs-ext
    kroki-fetch-diagram: true