site:
  title: Implicated
  url: https://docs.implicated.com
  start_page: open-feign::index.adoc
content:
  sources:
    - url: ../feign-docs
      start_paths:
        - docs
      branches: HEAD
ui:
  bundle:
    url: https://raw.githubusercontent.com/implicated/asciidoc-publish-template/ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  clean: true

antora:
  extensions:
    - require: '@antora/lunr-extension'
asciidoc:
  extensions:
    - asciidoctor-highlight.js/
    - asciidoctor-plantuml
  attributes:
    experimental: ''
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlightjs-ext
    plantuml-server-url: http://www.plantuml.com/plantuml